//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int IdOrderDetail { get; set; }
        public string IdOrder { get; set; }
        public Nullable<int> Line { get; set; }
        public int IdProduct { get; set; }
        public Nullable<double> Quantity { get; set; }
        public int IdUm { get; set; }
    }
}
