//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int IdProduct { get; set; }
        public string Description { get; set; }
        public string CodeBar { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string IdUm { get; set; }
    }
}
