//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int IdVendor { get; set; }
        public string VendorName { get; set; }
        public string RFC { get; set; }
        public string Address { get; set; }
        public string IdCountry { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Url { get; set; }
    }
}
